containerPort: 8080
image:
  prefix: "gcr.io/featurehub/mr"
  tag: "1.2"
resources:
  requests:
    memory: "256Mi"
    cpu: "100m"
  limits:
    memory: "512Mi"
    cpu: "400m"
global:
  environment_name: ci
