name: counter_e2e
description: An app built using Flutter for web

environment:
  # You must be using Flutter >=1.5.0 or Dart >=2.3.0
  sdk: '>=2.3.0-dev.0.1 <3.0.0'

dependencies:
  rxdart: 0.22.0
#  ogurets:
#    path: /Users/richard/projects/dart/ogurets
  counterapi:
    path: ../dart_api
  openapi_dart_common: ^2.0.0
  collection: ^1.14.11
dev_dependencies:
  ogurets: ^3.1.5
  pedantic: ^1.0.0
  test: ^1.6.5

