name: counterapi
version: 1.0.0
description: OpenAPI API client
environment:
  sdk: '>=2.2.0 <3.0.0'
dependencies:
  http: '>=0.11.1 <0.13.0'
  openapi_dart_common: ^1.0.1
  collection: ^1.14.11
dev_dependencies:
  test: ^1.3.0
